### ISSUE TITLE
Optimize sequencer module to avoid using "string" arguments as function input

### ISSUE THREAD

**Issue by kodsurf** [RobertK66/obc_1769_core#52] opened 2022-10-19 20:45 UTC
Use custom datastructure as an input to sequencer functions instead of "string" arguments.  Avoid using atoi() .

**Comment by kodsurf** [comment] 2022-11-14 22:04
https://github.com/RobertK66/obc_1769_core/commit/b44770b5c700a7a1b92456ff4887357d6e9821cf


Switched to arguments. Full redesign of parser. 

Looks like no more hardfault.  

I will leave it running for a night on a repeat sequence. Will see how stable

**Comment by kodsurf** [comment] 2022-11-14 22:20
https://github.com/RobertK66/obc_1769_core/commit/608ead21db0245cc2ee4812a1ef1d2bc3a2af032

![image](https://user-images.githubusercontent.com/66519643/201779863-0087e9b5-57b5-419a-a213-ab4de2a2623d.png)

Great news ! I am sending SET requests with 2Hz frequency and thruster is able to handle it now.

Bad news - Hardfault will still ocure if I try sending "5" command too often manually during execution.

I set sequence 1 (which just sends set requests) on repeat and left it running. Will see if it would be able to handle without hardfault, if nothing else is interfering with OBC.

**Comment by RobertK66** [comment] 2022-11-15 07:46
As our design discussions advance I am not sure about this issue any more. But lets discuss this in a Teams session....

**Comment by RobertK66** [comment] 2022-11-24 11:18
I close this now for API calls I think ewe can/should go on wth argc argv Commands!

**Closed as completed by RobertK66** 2022-11-24 11:18 UTC

**Comment by kodsurf** [comment] 2022-11-24 11:45
You mean we should continue using argv argc in sequencer ?


![image](https://user-images.githubusercontent.com/66519643/203776326-76e2ed98-3573-415c-ad6e-e71a22db4d98.png)
can we use advantage of both approaches by uncommenting line 48 here ?

flexible string argv could be one of elements in custom structure

**Comment by RobertK66** [comment] 2022-11-24 12:13
Yes, I think maybe it is more practical for now and maybe also for flight version(!?)
It will be easier for script storage and upload, but this is for sure a design discussion and not a bug/issue to be discussed,,,
